#!/bin/bash
source cabecalho
mt=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f2)
mf=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f4)
mb=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f6)
ml=$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f7)
[[ -e /etc/bash.bashrc-bakup ]] && _autorun="\033[1;32m${txt[10]}" || _autorun="\033[1;31m${txt[11]}"
echo -e "${cor[1]} ○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○ ${cor[0]}"
echo -e "${cor[2]} ⌐╦╦═─ ${cor[5]} ${txt[4]} @ChumoGH"
echo -e "M Total:" $mt "  ●   \033[1;32mM Libre:" $mf  
echo -e "M Usable:" $ml"  ●   M Cache:" $mb
echo -e "${cor[1]} ☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆ ${cor[0]}"
echo -e "${cor[2]} [0] >${cor[4]} ${txt[13]}"
echo -e "${cor[2]} [1] >${cor[3]} ${txt[5]}"
echo -e "${cor[2]} [2] >${cor[3]} ${txt[6]}"
echo -e "${cor[2]} [3] >${cor[0]}\033[0;33m [!]\033[1;32m OPTIMIZAR VPS "
echo -e "${cor[2]} [4] >${cor[0]}\033[1;31m [!]\033[1;31m REMOVER CHUMOGH●SCRIP"
echo -e "${cor[2]} [5] >${cor[3]} ${txt[12]}"
echo -e "${cor[2]} [6] >${cor[3]} ${txt[20]} $VERIFICAR_PID"
echo -e "${cor[2]} [7] >${cor[3]} ${txt[26]}"
echo -e "${cor[2]} [8] >${cor[3]} ${txt[322]} $_autorun"
echo -e "${cor[2]} [9] >${cor[3]} ${txt[256]}"
echo -e "${cor[1]} ☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆☆  ${cor[0]}"
